name: Maven Deploy Snapshot

on:
  push:
    branches:
      - devel
permissions:
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: corretto
          cache: maven
          overwrite-settings: false
      - name: Set up Node 10
        uses: actions/setup-node@v3
        with:
          node-version: 10.x
      - name: Build with Maven
        run: mvn --settings .github/settings.xml -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_READ_TOKEN: ${{ secrets.PACKAGE_READ_TOKEN }}
